marko-js/language-server

clients/vscode/package-lock.json, clients/vscode/src/extension.ts, package-lock.json, package.json, server/package-lock.json, server/package.json, server/src/server.ts, server/src/service.ts, server/src/util/typing.d.ts
I also ran formatter on one of the files and change spacing on it
=> Added pretty-print formatting

clients/vscode/package-lock.json, clients/vscode/package.json, server/package.json, server/src/services/javascript.ts, server/src/util/autocomplete.ts, server/src/util/document.ts, server/src/util/javascript.ts, server/src/util/marko.ts, server/src/util/paths.ts, server/src/util/stylesheet.ts
TODOs still in progress
- Need to parse partial files, for javascript
- Need to parse html attribute arguments as javascript
- Need to load typescript compiler from local project and use the projects config (although for later since we don't fully support typescript)
=> Added javascript autocomplete and fixed issues with style

.changeset/config.json, .changeset/friendly-cougars-jam.md, .github/workflows/ci.yml, clients/vscode/CHANGELOG.md, clients/vscode/package.json, package.json, pnpm-lock.yaml, server/CHANGELOG.md
Fix issue with vscode extension not including demo images.
Misc pnpm/changesets config improvements, including using GitHub changelogs.
=> Config fixes

.changeset/nine-points-perform.md, clients/vscode/syntaxes/marko.tmLanguage.json
Couple syntax highlighting improvements for embedded typescript.
=> fix(marko-vscode): improve typescript highlighting

.changeset/little-queens-help.md, .changeset/mighty-kangaroos-smoke.md, .changeset/wild-wombats-drum.md, clients/vscode/syntaxes/marko.tmLanguage.json
Improves syntax highlighting for style tags/blocks and tag variables.
=> Highlight fixes

.github/workflows/ci.yml
Attempt to use known email for GH action to avoid CLA issue.
=> chore: attempt to fix gh actions CLA

.changeset/beige-trains-lick.md, .changeset/fifty-kangaroos-attack.md, clients/vscode/syntaxes/marko.tmLanguage.json
marko-vscode
* Gives control flow tags a unique color.
* Improves highlighting for typescript types on a tag variable.
=> More highlight improvements

.changeset/loud-beers-deny.md, package.json, pnpm-lock.yaml, server/package.json
Upgrades all package dependencies.
=> chore: upgrade deps

.changeset/fuzzy-melons-tell.md, clients/vscode/src/__tests__/hover.test.ts, clients/vscode/src/__tests__/rename.test.ts, server/src/index.ts, server/src/service/index.ts, server/src/service/stylesheet/index.ts, server/src/service/types.ts
Implements rename provider (currently just for stylesheets).
=> feat: add rename provider

.changeset/clever-impalas-count.md, server/src/index.ts, server/src/service/index.ts, server/src/service/stylesheet/index.ts, server/src/service/types.ts
Implements document color provider (currently for stylesheets).
=> feat: add document color provider

.changeset/soft-garlics-raise.md, clients/vscode/src/__tests__/references.test.ts, server/src/index.ts, server/src/service/index.ts, server/src/service/stylesheet/index.ts, server/src/service/types.ts
Implements references provider (currently for stylesheets).
=> chore: implement references provider

.changeset/nasty-spies-think.md, .changeset/olive-mails-clap.md, server/src/index.ts, server/src/service/index.ts, server/src/service/marko/complete/AttrValue.ts, server/src/service/marko/complete/index.ts, server/src/service/marko/document-links/extract.ts, server/src/service/marko/document-links/index.ts, server/src/service/marko/index.ts, server/src/service/marko/util/is-document-link-attr.ts, server/src/service/stylesheet/extract.ts, server/src/service/stylesheet/index.ts, server/src/service/types.ts, server/src/utils/file-system.ts, server/src/utils/resolve-url.ts
Adds file system auto completions for css values and for a subset of native tags.
Also includes some refactoring to avoid mutating results from the stylesheet language service.
=> file system completions

.changeset/bright-windows-argue.md, .changeset/metal-toes-peel.md, .changeset/six-fans-relax.md, .vscode/tasks.json, clients/vscode/build.mts, clients/vscode/src/__tests__/diagnostics.test.ts, clients/vscode/syntaxes/marko.tmLanguage.json, package-lock.json, package.json, server/build.mts, server/package.json, server/src/service/marko/validate.ts
* Fixes syntax highlighting when a tag variable is followed by a comma.
* Fixes an issue where invalid diagnostics were being displayed.
* Upgrades dependencies.
=> fix: highlight improvement, avoid invalid diagnostics, deps upgrades.

.changeset/cyan-dodos-thank.md, packages/language-tools/marko.internal.d.ts
Fixes an issue where in several cases tags were accepting additional inputs that were not specified in the tags input type.
=> fix: tag type constraints issue

.changeset/eleven-otters-whisper.md, .changeset/tasty-socks-greet.md, package-lock.json, package.json, packages/language-server/package.json, packages/language-server/src/service/script/index.ts, packages/language-server/src/service/script/util/print-jsdoc-tag.ts, packages/language-tools/package.json
Make the documentation output from hovering over typescript values more in line with the typescript language server.
=> TypeScript hover documentation fixes

packages/vscode/README.md
=> docs: update link to gif

packages/language-server/src/service/script/index.ts
Fix an issue that shows up in monorepo/workspaces:
All open files were treated as part of the project.  This meant a file part of a TS project would complain about type definitions being present if it were loaded in a JS project and vice-versa.
Additionally a cache on project config was added since the fix involved the addition of project lookups for all open files.
=> fix: workspaces with different project types (ts/js)

.changeset/olive-pumas-provide.md, packages/language-tools/marko.internal.d.ts
Fix a bug with attr tags within for loops & if statements
=> For attr tag types

.changeset/neat-shirts-smell.md, packages/language-server/src/service/html/axe-rules/rule-exceptions.ts
=> fix(axe-core): remove false positive

.changeset/happy-mangos-cough.md
- Add changeset to `@marko/type-check` for changes in #244
=> chore: add changeset

packages/vscode/syntaxes/marko.tmLanguage.json
- Add `server` and `client` as reserved top-level statements
- We may be adding `server` and `client` as alternatives to `static`, which are only executed in their respective environments
=> feat: add `server` and `client` statements

.changeset/big-books-check.md, packages/language-server/src/service/script/index.ts, packages/vscode/syntaxes/marko.tmLanguage.json
=> fix(typescript): override rootDir to root of project

.changeset/good-guests-itch.md, packages/type-check/src/run.ts
- Resolves #269
- Remove `removeComments: true` config
- See #269
=> feat(type-check): use .tsconfig options for printer

.changeset/famous-cherries-clap.md, packages/language-tools/marko.internal.d.ts
=> fix: reduce recursion in complex input types

.changeset/curvy-parrots-shake.md, packages/language-server/src/service/html/axe-rules/rule-exceptions.ts
A11y linter
- `empty-heading` rule had some false positives
- Bonus change: refactored file to clean it up and help with understanding
=> fix(axe-core): remove false positive and refactor file

.changeset/tall-hairs-scream.md, package-lock.json, packages/language-server/package.json, packages/language-server/src/__tests__/fixtures/script/if-tag/__snapshots__/if-tag.expected/index.md, packages/language-server/src/__tests__/fixtures/script/if-tag/__snapshots__/if-tag.expected/index.ts, packages/language-server/src/__tests__/fixtures/script/tag-var-hoisting-from-control-flow/__snapshots__/tag-var-hoisting-from-control-flow.expected/index.html, packages/language-server/src/__tests__/fixtures/script/tag-var-hoisting-from-control-flow/__snapshots__/tag-var-hoisting-from-control-flow.expected/index.md, packages/language-server/src/__tests__/fixtures/script/tag-var-hoisting-from-control-flow/__snapshots__/tag-var-hoisting-from-control-flow.expected/index.ts, packages/language-server/src/__tests__/fixtures/script/tag-var-hoisting-from-control-flow/index.marko, packages/language-tools/package.json, packages/language-tools/src/extractors/script/index.ts
=> fix: if tag scope hoisting
