marko-js/language-server

clients/vscode/package.json

Previous publisher name is not accessible anymore

Updated publisher name to one that is available

---

.gitmodules
README.md
package.json

language-marko
Adds the updated `language-marko` plugin (converted to use atom-languageclient).

feat(language-marko): add atom client

---

.changeset/wise-doors-lie.md
.vscode/launch.json
clients/vscode/package.json
package.json
pnpm-lock.yaml
server/package.json
server/src/index.ts
server/src/utils/compiler.ts

Fixes an issue caused by recently changing to bundle the plugin.
After bundling the `prettier-plugin-marko` could no longer be found and also if Marko was not locally installed some editor functionality would not work.

fix: upgrade deps, issue with formatting not finding parser

---

.changeset/curvy-sloths-think.md
clients/vscode/package.json

A previous dependency upgrade caused the vscode engine version to be out of sync. This PR upgrades it properly.

fix: vscode engine version

---

.github/workflows/ci.yml

Make gh bot email compatible with CLA.

chore: use CLA compatible email for gh bot

---

.github/workflows/ci.yml

Switches back to the original GH bot email in the config.
Previous change was a test to see if it should change to work with the Easy CLA, turns out not necessary.

chore: check if gh action email change was needed

---

.changeset/strong-phones-hide.md
clients/vscode/syntaxes/marko.tmLanguage.json

marko-vscode
Fix highlighting for manual .css extension on style blocks, eg `style.module.css { /* ... */ } `.

fix(marko-vscode): highlighting for manual .css extension on style blocks

---

.changeset/polite-hairs-arrive.md
clients/vscode/syntaxes/marko.tmLanguage.json

marko-vscode
Fixes an issue where tags that were prefixed with builtin tag names were being highlighted as builtin tags, eg `<for-virtualized>`

fix: incorrect highlighting as builtin tag for some custom tags

---

.changeset/lucky-hornets-pump.md
clients/vscode/syntaxes/marko.tmLanguage.json

marko-vscode
Improves highlighting for the `html-comment` tag to:
* Support interpolations
* Highlight open tag attrs/var/etc
* Support concise mode
Also some small tweaks to the scope information for some concise mode syntaxes.

fix: improve html-comment and concise mode highlighting

---

.changeset/clever-points-grin.md
.changeset/olive-sloths-sell.md
.changeset/thin-jobs-joke.md
clients/vscode/syntaxes/marko.tmLanguage.json

marko-vscode
* Fix issue with unary expressions (eg typeof) in attribute values that were part of a member expression (eg input.typeof) incorrectly highlighting
* Improve attribute value highlighting when the value is unenclosed and spans multiple lines
* Make concise mode html delimiters more visible.

Syntax highlighting improvements 05 10 2020

---

.changeset/swift-carrots-smoke.md
clients/vscode/syntaxes/marko.tmLanguage.json

marko-vscode
Improves a few issues with syntax highlighting:
* Concise mode was not always properly tracking indentation.
* Comas after attributes were not always honored, especially after the default attribute.
* CDATA/Doctype were not always highlighting (normal comment was taking priority).
* Incorrect token type for tag variable type colon.

fix: improve syntax highlighting

---

.changeset/clean-schools-relax.md
clients/vscode/syntaxes/marko.tmLanguage.json

Add error highlighting when an extraneous html closing tag is found

feat: show error highlighting on extra close tags

---

.changeset/silent-wombats-hang.md
clients/vscode/syntaxes/marko.tmLanguage.json

Fixes an issue with concise tags being exited too early by the highlight grammar which ultimately broke bracket colorization.
Resolves #83

fix: better support bracket colorization

---

.changeset/clever-gorillas-laugh.md
clients/vscode/src/__tests__/colors.test.ts
clients/vscode/src/__tests__/highlight.test.ts
server/src/index.ts
server/src/service/index.ts
server/src/service/stylesheet/index.ts
server/src/service/types.ts

Implements document highlight provider (currently for stylesheets).

Document highlights provider

---

.changeset/short-rabbits-vanish.md
server/src/index.ts
server/src/service/index.ts
server/src/service/marko/document-links/extract.ts
server/src/service/marko/document-symbols/extract.ts
server/src/service/marko/document-symbols/index.ts
server/src/service/marko/index.ts
server/src/service/stylesheet/extract.ts
server/src/service/stylesheet/index.ts
server/src/service/types.ts

Implements the document symbol provider.
Also fixes an issue where the stylesheet providers and the document link providers were not visiting attribute tags.

feat: implement document symbols provider

---

.changeset/rare-suns-remain.md
clients/vscode/package.json

Enables the Marko formatter by default (no longer necessary to configure a default formatter for Marko files).

fix: enable formatter as a default config option

---

.changeset/swift-rings-marry.md
packages/language-server/src/service/script/index.ts

marko-vscode
Improves the location where `import` and `export` statements are injected with typescript.
Also ensures they are after any PRAGMA comments, eg `// @ts-check`.

feat: improve location of import/export insertions

---

.changeset/cold-kids-mix.md
.vscode/launch.json
package-lock.json
package.json
packages/language-server/package.json
packages/language-server/src/ts-plugin/host.ts
packages/language-tools/package.json
packages/language-tools/src/util/project.ts
packages/type-check/package.json
packages/vscode/build.mts

* Fixes a regression where trying to resolve a Marko file in a typescript file would cause the ts language server to crash.
* Fixes a regression where the default Marko core/internal runtimes were not being loaded.

fix: ts-plugin regression

---

.changeset/shiny-fishes-fix.md
packages/language-server/src/service/html/axe-rules/rule-exceptions.ts

Added extra filter for the following false positive:
```marko
span role=someDynamicValue
```

fix(axe-core): add filter for false positive

---

.changeset/brave-points-eat.md
packages/language-server/src/__tests__/fixtures/script/for-tag/__snapshots__/for-tag.expected/index.md
packages/language-server/src/__tests__/fixtures/script/for-tag/index.marko
packages/language-tools/marko.internal.d.ts

Resolves https://github.com/marko-js/language-server/issues/228
Currently because of the special transformations we have to do on control flow tags their types exist in this project.
However the `by` attribute for `<for>` tags in the tags api was missed.

fix: add for tag by attribute types

---

.changeset/gorgeous-ducks-reflect.md
packages/language-tools/src/processors/index.ts
packages/language-tools/src/processors/marko.ts
packages/type-check/src/run.ts

When using `@marko/type-check` to emit js files for a native es module package the output files will not have the resolved extension included for relative imports.
This is actually a TypeScript design that they say is working as intended:
https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-specifiers-are-not-transformed
However besides being very strange to import non existing `.js` files, it also doesn't work in `jest`, `vite`, `vitest`, `webpack`, `rollup`, or `esbuild`.
So this PR handles it for you. With this change `.js` extensions are automatically added to output relative import paths.

feat: add .js extension for mtc output

---

.changeset/clever-onions-bathe.md
packages/language-server/src/__tests__/fixtures/script/split-component-d-ts/__snapshots__/split-component-d-ts.expected/index.md
packages/language-server/src/__tests__/fixtures/script/split-component-d-ts/components/fancy-button/component.d.ts
packages/language-server/src/__tests__/fixtures/script/split-component-d-ts/components/regular-button/component-browser.d.ts
packages/language-server/src/__tests__/fixtures/script/split-component-d-ts/index.marko
packages/language-tools/src/extractors/script/util/get-component-filename.ts

- When detecting whether a `.marko` file had a `component.ts`, we were searching for other files that had the same base name followed by `component`. However, instead of searching for `name.component.d.ts` we were searching for `name.d.component.ts`.
- It seems to suffice to simply trim the `.d` from the basename, but there may be some edge case I'm missing.

fix(language-server): handle `.d.marko` split component

---

.changeset/nasty-books-exercise.md
packages/language-tools/src/extractors/script/util/get-component-filename.ts

- Fixes bug introduced in #244 when filename includes special regex characters (i. e. `+layout.marko`)

Extra marko run characters

---

.changeset/fair-flies-worry.md
packages/vscode/package.json
packages/vscode/syntaxes/embedded.marko.tmLanguage.json

Simple addition to highlight Marko code blocks inside Markdown and MDX files

Add injection grammar for markdown and MDX

---

.changeset/fast-walls-unite.md
packages/type-check/src/run.ts

@marko/type-check
Currently a tsconfig with `declarationMap: true` will cause an error for Marko files.
This PR fixes the issue by avoiding outputting any sourcemaps for the Marko files. (Ideally this is addressed in the future).

fix: no longer error with declaration map output

---

.changeset/tall-pears-prove.md
packages/language-server/src/service/index.ts
packages/language-server/src/service/marko/format.ts
packages/language-server/src/service/marko/index.ts
packages/vscode/package.json
packages/vscode/src/index.ts

- Allow formatting with forced concise or HTML mode

feat: format with forced mode

---

.changeset/red-starfishes-smell.md
packages/language-server/src/__tests__/fixtures/html/alt-text/__snapshots__/alt-text.expected/index.md
packages/language-server/src/__tests__/fixtures/html/alt-text/index.marko
packages/language-tools/src/extractors/html/index.ts

- `language-server`
- Remove modifiers from attributes in the extracted static html
- Accessibility linter had false positives when an attribute that helped with accessibility included a modifier.

fix(html-extractor): remove modifiers

---

.changeset/big-games-peel.md
packages/language-server/src/__tests__/fixtures/script/attr-tags-for-narrowing/__snapshots__/attr-tags-for-narrowing.expected/index.md
packages/language-server/src/__tests__/fixtures/script/attr-tags-for-narrowing/components/list.marko
packages/language-server/src/__tests__/fixtures/script/attr-tags-for-narrowing/index.marko
packages/language-tools/marko.internal.d.ts

Type narrowing wasn't working for attr tags in a for loop, i.e.
```marko
<list>
<for|item| of=items>
<@item size="small"/>
// ^^^^^^^ ERROR: `string` is not assignable to `"small"`
</for>
</list>
```
```marko
// list.marko
export interface Input {
item?: Marko.RepeatableAttrTag<{
size?: "small" | "large"
}>
}
```
- Helps with ebay/ebayui-core#2282

fix: add const return to forAttrTag helpers

---

.changeset/breezy-flies-check.md
packages/language-server/src/__tests__/fixtures/html/focus-order-semantics/__snapshots__/focus-order-semantics.expected/index.md
packages/language-server/src/__tests__/fixtures/html/focus-order-semantics/index.marko
packages/language-server/src/service/html/axe-rules/axe-rules.ts
packages/language-server/src/service/html/axe-rules/generate-axe-rules.ts
packages/language-server/src/service/html/axe-rules/rule-exceptions.ts

- `language-server`
- Current linter has experimental rules enabled. The fix disables these rules. 
- Fixes #275

fix(axe-core): disabled experimental rules

---

.changeset/bright-baboons-thank.md
packages/language-server/src/__tests__/fixtures/script/if-tag/__snapshots__/if-tag.expected/index.md
packages/language-server/src/__tests__/fixtures/script/if-tag/index.marko
packages/language-tools/src/extractors/script/index.ts

If chains caused TS errors
```marko
if
else-if
if
else-if
//^^^^^^^ isn't detected properly
else
```
Fixes the above

fix: nested if chains

---

.changeset/great-cars-poke.md
packages/language-server/src/__tests__/fixtures/script/attr-tag-target-property/__snapshots__/attr-tag-target-property.expected/index.md
packages/language-server/src/__tests__/fixtures/script/attr-tags-params-js/__snapshots__/attr-tags-params-js.expected/index.md
packages/language-server/src/__tests__/fixtures/script/attr-tags-params-js/components/child.marko
packages/language-server/src/__tests__/fixtures/script/attr-tags-params-js/index.marko
packages/language-server/src/__tests__/fixtures/script/attr-tags-params-js/marko.json
packages/language-server/src/__tests__/fixtures/script/attr-tags-params/__snapshots__/attr-tags-params.expected/index.md
packages/language-server/src/__tests__/fixtures/script/attr-tags-params/components/child.marko
packages/language-server/src/__tests__/fixtures/script/attr-tags-params/index.marko
packages/language-server/src/__tests__/fixtures/script/recursive-input-scope-hoist/__snapshots__/recursive-input-scope-hoist.expected/index.md
packages/language-server/src/__tests__/fixtures/script/recursive-input-scope-hoist/index.marko
packages/language-tools/src/extractors/script/index.ts

- Tag parameters for attr tags now have proper types without need for being explicit
```marko
my-tag
@attrTag
@attrTag|data|
${data.a}
// ^ inferred!
```
> [!Note]
> When there _is_ an error in certain attr tags now, hoisting breaks and an additional error shows up on the first attr tag in addition to the broken one. This is evident in the `recursive-input-scope-hoist`, but since that's not really the purpose of the test I modified it to remove the error.

feat(ts): improve type inference for attr tags

---

.changeset/funny-steaks-run.md
package-lock.json
package.json
packages/language-server/package.json

- Fixes #297 
- Moves dependencies from the root level `package.json` to the one for `language-server`
- Looks like I broke the language server back when I added axe-core support in #188 😅

fix(language-server): move dependencies to package.json

---

.changeset/honest-numbers-add.md
package-lock.json
packages/language-server/package.json
packages/language-tools/package.json
packages/language-tools/src/extractors/script/util/attach-scopes.ts
packages/language-tools/src/parser.ts
packages/vscode/syntaxes/marko.tmLanguage.json

- Treat `client` and `server` statements like `static`
- Add support for the `satisfies` keyword
- Change the way explicit type annotations work for `let`

fix(ts): client, server, satisfies, explicit type annotations

---

.changeset/bright-windows-fly.md
packages/language-tools/src/extractors/script/index.ts
packages/language-tools/src/extractors/script/util/attach-scopes.ts
packages/language-tools/src/extractors/script/util/is-text-only-script.ts

Partially resolve #313 by adding more checks before processing a `<script>` as javascript/typescript code in the output.
@vwong FYI this change was made to align with the proposed future change of the tags api to make it such that the `<script>` tag is processed by Marko to act like the `<effect>` of the tags api preview. (https://github.com/marko-js/website/blob/next/src/routes/docs/core-tag.md#script.

fix: stricter check before processing a script as javascript

---

.changeset/new-dots-scream.md
packages/language-server/src/__tests__/fixtures/script/for-tag-attr-tags/__snapshots__/for-tag-attr-tags.expected/index.md
packages/language-server/src/__tests__/fixtures/script/for-tag-attr-tags/components/my-table.marko
packages/language-server/src/__tests__/fixtures/script/for-tag-attr-tags/index.marko
packages/language-tools/marko.internal.d.ts
packages/language-tools/src/extractors/script/index.ts

No longer breaks:
```marko
<my-table>
<for|row| of=[
{ foo: "a", bar: "b" },
{ foo: "c", bar: "d" },
]>
<@row>
// ^?
<@cell>${row.foo}</@cell>
// ^?     ^?
<@cell>${row.bar}</@cell>
</@row>
</for>
</my-table>
```

fix(ts): nested attr tags in for-of loops

---

.changeset/rude-peaches-scream.md
packages/language-tools/src/extractors/script/index.ts

Fix a logical mistake made by @LuLaValva earlier today 🥵

fix(ts): flawed logic from last version

---

.changeset/happy-glasses-trade.md
packages/language-server/src/__tests__/fixtures/script/import-without-types/__snapshots__/import-without-types.expected/index.ts
packages/language-server/src/__tests__/fixtures/script/import-without-types/components/Child/marko-tag.json
packages/language-server/src/__tests__/fixtures/script/import-without-types/components/child-other/marko-tag.json
packages/language-tools/src/extractors/script/index.ts

Ignore missing types for non-Marko templates (eg. where the resolved template is a .js renderer and has no types)

fix: ignore tag types for non-marko templates

---

.changeset/violet-cougars-rescue.md
packages/language-server/src/__tests__/fixtures/script/tag-param-mutation/__snapshots__/tag-param-mutation.expected/index.html
packages/language-server/src/__tests__/fixtures/script/tag-param-mutation/__snapshots__/tag-param-mutation.expected/index.md
packages/language-server/src/__tests__/fixtures/script/tag-param-mutation/__snapshots__/tag-param-mutation.expected/index.ts
packages/language-server/src/__tests__/fixtures/script/tag-param-mutation/index.marko
packages/language-tools/marko.internal.d.ts

- When a tag body was unreachable, an error was thrown elsewhere in the template after an attempt to hoist its tag vars.
```marko
<for|_bodyUnreachable| of=[]>
<let/ts_will_try_to_hoist_this/>
</for>
<script>
ts_will_try_to_hoist_this;
// ^? Before this was `any`, now it's `never`
</script>
```

fix(ts): tag param for unreachable body

---

.changeset/early-baboons-swim.md
packages/language-server/src/__tests__/fixtures/script/comments/__snapshots__/comments.expected/index.ts
packages/language-server/src/__tests__/fixtures/script/comments/index.marko
packages/language-tools/src/extractors/script/index.ts

- HTML comments are transformed to JS comments in the extractor, so `` transforms to `/* */ */` which is invalid JS
- Break up closing JS comments with a `\` when they're inside HTML comments

fix(script extractor): JS comments in HTML comments

---

.changeset/tasty-carrots-compete.md
packages/language-tools/src/extractors/script/index.ts

In some niche templates, the lack of a semicolon at the end of this statement causes problems

fix(script extractor): add semicolon

---

.changeset/ten-seas-shop.md
packages/language-tools/marko.internal.d.ts

- As it turns out, interfaces do _not_ extend `Record<string, unknown>` but they do extend `Record<string, any>` ([TS Playground example](https://www.typescriptlang.org/play/?ts=5.8.3#code/C4TwDgpgBAKhDOwA8MB8UC8soQB7AgDsATeKAJQgGMB7AJ2KUToEtCBzAGigFdCBrQjQDuhdAH4oARigAuKAAYAUErYE6AMwCGVaAElC67bqgBvJVEtQNNGvOZt2SgL4rQkWOGhZzVqFvtgVg4XNy8oAEFMWARkAyMdCFQlAHoUqwA9cTCPACFouEQUL2S0zOygA))
- This impacted type stubs like this
```ts
declare module "@module/src/index.marko" {
interface MyInput {
foo: string;
bar: number;
}
const file: Template<MyInput>;
export default file;
}
```
- After switching from `unknown` to `any`, these type stubs seem to work properly

fix: change Record<*, unknown> to Record<*, any>

---

.changeset/witty-ghosts-pump.md
packages/language-server/src/service/marko/complete/Import.ts
packages/language-server/src/service/marko/complete/index.ts
packages/language-server/src/ts-plugin/host.ts
packages/type-check/src/run.ts

Adds support for the import tag shorthand in typescript / js files.
```
import Tag from "<tag>";
```

feat: support tag import shorthands in ts files

---

.changeset/few-oranges-juggle.md
packages/language-tools/marko.internal.d.ts

`@marko/language-tools`
Marko 6 supports writing:
```
<for|user| of=users by="id">
${user.firstName} ${user.lastName}
</for>
```
as shorthand for
```
<for|user| of=users by=user => user.id>
${user.firstName} ${user.lastName}
</for>
```
But the Typescript definitions do not reflect this.
To fix Typescript definitions

chore: fix for-of types
